'use client';
import {useState} from 'react';
import Link from 'next/link';
import {SearchResult} from '@/lib/search/engine';
import {labels,number,price} from '@/lib/domain';
export function DecisionTools({result:r,state}:{result:SearchResult;state:string}){
 const [choice,setChoice]=useState('');const [filter,setFilter]=useState('');const chosen=r.alternatives.find(x=>x.id===choice);
 const valid=r.curve.filter(x=>x.utility!==null);const bestUtility=Math.max(0,...valid.map(x=>x.utility!));const knee=valid.find(x=>x.utility!>=bestUtility*.95);
 const scenarios=r.sensitivity?.scenarios.filter(x=>x.changed)??[];
 return <div className="decision-tools">
 {r.stretch&&<section className="panel"><h3>کمی بالاتر از بودجه، ولی ارزش بررسی داره</h3><Link href={`/product/${r.stretch.product.id}?state=${state}`}>{r.stretch.product.displayName}</Link><p>{price(r.stretch.product.price)} · حداقل ۵ امتیاز سود تخمینی بیشتر؛ این گزینه در سه پیشنهاد داخل بودجه نیست.</p></section>}
 <details className="panel" open={r.intent.action==='save'}><summary>ارزون‌تر هم میشه؟</summary>{r.saving?<><p>با {price(r.saving.saved)} کمتر، حدود {number(r.saving.retained*100)}٪ از سود تخمینی انتخاب اول حفظ می‌شود.</p><Link href={`/product/${r.saving.nextId}?state=${state}`}>{r.saving.nextName} ←</Link><p>{r.saving.losses.length?r.saving.losses.map(x=>`${labels[x.key]}: ${number(x.delta)} امتیاز کمتر`).join('؛ '):'در شاخص‌ها افت ۸ امتیازی ثبت نشده.'}</p><small>ارزان‌ترین نسخه واجد تمام شرط‌ها با حداقل ۹۳٪ سود و پوشش داده مشابه؛ مبنا قیمت نمونه است.</small></>:<p>گزینه ارزان‌تری با حفظ ۹۳٪ سود و شرط‌های فعلی پیدا نشد.</p>}</details>
 <details className="panel"><summary>چرا فلان مدل نه؟</summary><label>جست‌وجوی مدل<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="مثلاً S23 FE"/></label><label>مدل و نسخه<select value={choice} onChange={e=>setChoice(e.target.value)}><option value="">یک گوشی انتخاب کن</option>{r.alternatives.filter(x=>x.name.toLowerCase().includes(filter.toLowerCase())).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{chosen&&<div className="notice"><bdi>{chosen.name}</bdi><p>{price(chosen.price)}</p>{chosen.reasons.map(x=><p key={x}>{x}</p>)}<Link href={`/product/${chosen.id}?state=${state}`}>مشخصات و امتیاز کامل</Link></div>}</details>
 <details className="panel"><summary>چی می‌تونه پیشنهاد اول رو عوض کنه؟</summary><p>در {number((r.sensitivity?.stableRatio??0)*100)}٪ سناریوهای تغییر ۲۰٪ وزن، مدل اول ثابت ماند.</p>{scenarios.length?scenarios.slice(0,6).map(x=><p key={`${x.key}-${x.factor}`}>{labels[x.key]} {x.factor>1?'۲۰٪ مهم‌تر':'۲۰٪ کم‌اهمیت‌تر'} شود: <bdi>{x.winnerName}</bdi></p>):<p>تغییر کوچک وزن‌ها مدل اول را عوض نکرد؛ سناریوهای اولویت قوی و بودجه را در ادامه ببین.</p>}{r.counterfactuals?.map(x=><p key={x.key}>{x.label}: <bdi>{x.winnerName??'گزینه‌ای نیست'}</bdi></p>)}</details>
 <details className="panel"><summary>بودجه و سود انتخاب؛ کجا هزینه بیشتر کم‌اثر می‌شود؟</summary><p>شرط‌های غیربودجه‌ای ثابت مانده‌اند؛ بودجه‌های بالاتر فقط سناریو هستند.</p><svg className="utility-chart" viewBox="0 0 600 210" role="img" aria-label="نمودار سود تخمینی در شش بودجه"><path d="M35 10v160h545" fill="none" stroke="#d8d8d8"/>{r.curve.map((x,i)=>x.utility===null?null:<g key={x.budget}><circle cx={55+i*100} cy={170-x.utility*1.45} r="5" fill="#d72e37"/><text x={55+i*100} y={155-x.utility*1.45} textAnchor="middle">{Math.round(x.utility)}</text><text x={55+i*100} y="195" textAnchor="middle">{number(x.budget/1e6)} M</text></g>)}<polyline points={r.curve.map((x,i)=>x.utility===null?'':`${55+i*100},${170-x.utility*1.45}`).join(' ')} fill="none" stroke="#d72e37" strokeWidth="2"/></svg>{knee&&<p className="notice">در بازه بررسی‌شده، سقف {price(knee.budget)} حداقل ۹۵٪ بیشترین سود را می‌دهد؛ بیشتر از آن حداکثر {number(bestUtility-knee.utility!)} امتیاز بهبود دارد.</p>}<div className="table-scroll"><table><thead><tr><th>بودجه نمونه</th><th>انتخاب</th><th>سود</th></tr></thead><tbody>{r.curve.map(x=><tr key={x.budget}><td>{price(x.budget)}</td><td>{x.winnerName??'بدون نتیجه'}</td><td>{number(x.utility)}</td></tr>)}</tbody></table></div></details>
 </div>
}
